### ISSUE TITLE
Add shortcut methods

### ISSUE THREAD

**Issue by Amzani** [smoya/asyncapi-adoption-metrics#1]
Linked to this comment
https://github.com/asyncapi/community/issues/879#issuecomment-1754816710

**Comment by smoya** [comment]
We first need to know which metrics we want to collect. cc @fmvilas as you wanted to provide this.

**Comment by smoya** [comment]
With the current set of methods, we are able to cover basic metrics for executed actions/cmd, such as CLI `validate`, `generate`, etc.
This can be considered a good starting point so we can close this issue and mark it as done for the first iteration.

**Comment by smoya** [comment]
/progress 100 Current set of methods are able to cover basic metrics for executed actions/cmd, such as CLI validate, generate, etc.
