### ISSUE TITLE
Finish New Relic sink

### ISSUE THREAD

**Issue by smoya** [smoya/asyncapi-adoption-metrics#9]
#### Reason/Context
ATM, [New Relic](https://github.com/smoya/asyncapi-adoption-metrics/blob/main/src/sink.ts#L17) sink is not finished so it won't work.

#### Description
Finish the work pending for the sink so we can send metrics to New Relic.

**Comment by peter-rr** [comment]
@smoya I guess we could consider this issue is already solved by #13, right?

**Comment by smoya** [comment]
> @smoya I guess we could consider this issue is already solved by #13, right?

Yup!
